# -*- coding: utf-8 -*-
"""AIP_q3_ass4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f-f7oPeWl8DJZnIpcGvxu3pjGsixOgju
"""

!wget https://github.com/WongKinYiu/yolov7/releases/download/v0.1/yolov7.pt

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/WongKinYiu/yolov7.git
# %cd /content/yolov7

from google.colab import drive
drive.mount('/content/drive')

!pip install -qr requirements.txt
!pip install --upgrade numpy



!python3 train.py --batch 8 --cfg /content/drive/MyDrive/AIP/Assignment_4/hw5/YOLO/yolov7.yaml --data /content/drive/MyDrive/AIP/Assignment_4/hw5/YOLO/yolov7-main/object_detection/data.yaml --weights /content/yolov7.pt --epochs 50 --img 416

# Command to perform object detection inference using YOLOv7
!python detect.py --weights /content/yolov7/runs/train/exp5/weights/best.pt --img 416 --conf 0.4 --source /content/drive/MyDrive/AIP/Assignment_4/hw5/YOLO/yolov7-main/object_detection/test/images

# Command to evaluate the performance of the trained YOLOv7 model on the test dataset
!python test.py --weights /content/yolov7/runs/train/exp5/weights/best.pt --data /content/drive/MyDrive/Assignment_4/hw5/YOLO/yolov7-main/object_detection/data.yaml --img-size 416

import shutil
import os
from google.colab import files

# Specify the folder path you want to download
folder_path = '/content/yolov7/runs/train/exp5'

# Zip the folder
shutil.make_archive('/content/yolov7/runs/train/exp5', 'zip', folder_path)

# Download the zip file
files.download('/content/yolov7/runs/train/exp5.zip')